// Generated by Melange
'use strict';

var Digest = require("bs-platform/lib/js/digest.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

var empty = Digest.string("");

function make(s) {
  if (s === empty) {
    return empty;
  } else {
    return s;
  }
}

var compare = Caml_obj.caml_compare;

function to_binary(s) {
  return s;
}

function of_binary_exn(s) {
  if (s.length !== 16) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "md5_lib.ml",
            16,
            22
          ],
          Error: new Error()
        };
  }
  return make(s);
}

function of_hex_exn(s) {
  return make(Digest.from_hex(s));
}

function string(s) {
  return make(Digest.string(s));
}

function bytes(s) {
  return make(Digest.bytes(s));
}

function subbytes(bytes, pos, len) {
  return make(Digest.subbytes(bytes, pos, len));
}

var length = 16;

var unsafe_of_binary = make;

var to_hex = Digest.to_hex;

exports.compare = compare;
exports.length = length;
exports.to_binary = to_binary;
exports.of_binary_exn = of_binary_exn;
exports.unsafe_of_binary = unsafe_of_binary;
exports.to_hex = to_hex;
exports.of_hex_exn = of_hex_exn;
exports.string = string;
exports.bytes = bytes;
exports.subbytes = subbytes;
/* empty Not a pure module */
