// Generated by Melange
'use strict';

var Sexp_grammar$negSexplib0 = require("./sexp_grammar.bs.js");

var ref_sexp_grammar = Sexp_grammar$negSexplib0.coerce;

var lazy_t_sexp_grammar = Sexp_grammar$negSexplib0.coerce;

function option_sexp_grammar(param) {
  return {
          TAG: /* Option */2,
          _0: param
        };
}

function list_sexp_grammar(param) {
  return {
          TAG: /* List */3,
          _0: {
            TAG: /* Many */1,
            _0: param
          }
        };
}

function array_sexp_grammar(param) {
  return {
          TAG: /* List */3,
          _0: {
            TAG: /* Many */1,
            _0: param
          }
        };
}

var empty_sexp_grammar = {
  TAG: /* Union */5,
  _0: /* [] */0
};

var unit_sexp_grammar = {
  TAG: /* List */3,
  _0: /* Empty */0
};

var bool_sexp_grammar = /* Bool */0;

var string_sexp_grammar = /* String */4;

var bytes_sexp_grammar = /* String */4;

var char_sexp_grammar = /* Char */1;

var int_sexp_grammar = /* Integer */2;

var float_sexp_grammar = /* Float */3;

var int32_sexp_grammar = /* Integer */2;

var int64_sexp_grammar = /* Integer */2;

var nativeint_sexp_grammar = /* Integer */2;

var opaque_sexp_grammar = empty_sexp_grammar;

var fun_sexp_grammar = empty_sexp_grammar;

exports.unit_sexp_grammar = unit_sexp_grammar;
exports.bool_sexp_grammar = bool_sexp_grammar;
exports.string_sexp_grammar = string_sexp_grammar;
exports.bytes_sexp_grammar = bytes_sexp_grammar;
exports.char_sexp_grammar = char_sexp_grammar;
exports.int_sexp_grammar = int_sexp_grammar;
exports.float_sexp_grammar = float_sexp_grammar;
exports.int32_sexp_grammar = int32_sexp_grammar;
exports.int64_sexp_grammar = int64_sexp_grammar;
exports.nativeint_sexp_grammar = nativeint_sexp_grammar;
exports.ref_sexp_grammar = ref_sexp_grammar;
exports.lazy_t_sexp_grammar = lazy_t_sexp_grammar;
exports.option_sexp_grammar = option_sexp_grammar;
exports.list_sexp_grammar = list_sexp_grammar;
exports.array_sexp_grammar = array_sexp_grammar;
exports.opaque_sexp_grammar = opaque_sexp_grammar;
exports.fun_sexp_grammar = fun_sexp_grammar;
/* No side effect */
