// Generated by Melange
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Sexp$negSexplib0 = require("sexplib0/./sexp.bs.js");

var a = {
  TAG: /* Atom */0,
  _0: "sdsd"
};

console.log(Sexp$negSexplib0.to_string(a));

var b = List.map;

exports.a = a;
exports.b = b;
/*  Not a pure module */
