// Generated by Melange
'use strict';

var Runtime_bsJs = require("./runtime_bs.js");

function fold_int64(prim, prim$1) {
  return Runtime_bsJs.Base_internalhash_fold_int64(prim, prim$1);
}

function fold_int(prim, prim$1) {
  return Runtime_bsJs.Base_internalhash_fold_int(prim, prim$1);
}

function fold_float(prim, prim$1) {
  return Runtime_bsJs.Base_internalhash_fold_float(prim, prim$1);
}

function fold_string(prim, prim$1) {
  return Runtime_bsJs.Base_internalhash_fold_string(prim, prim$1);
}

function get_hash_value(prim) {
  return Runtime_bsJs.Base_internalhash_get_hash_value(prim);
}

exports.fold_int64 = fold_int64;
exports.fold_int = fold_int;
exports.fold_float = fold_float;
exports.fold_string = fold_string;
exports.get_hash_value = get_hash_value;
/* ./runtime_bs.js Not a pure module */
