// Generated by Melange
'use strict';

var Sys0$negBase = require("./sys0.bs.js");
var Caml_bytes = require("bs-platform/lib/js/caml_bytes.js");
var BytesLabels = require("bs-platform/lib/js/bytesLabels.js");

var Primitives = {};

var create = Caml_bytes.caml_create_bytes;

var unsafe_blit = Caml_bytes.caml_blit_bytes;

var unsafe_to_string = BytesLabels.unsafe_to_string;

var max_length = Sys0$negBase.max_string_length;

var blit = BytesLabels.blit;

var blit_string = BytesLabels.blit_string;

var compare = BytesLabels.compare;

var copy = BytesLabels.copy;

var fill = BytesLabels.fill;

var make = BytesLabels.make;

var map = BytesLabels.map;

var mapi = BytesLabels.mapi;

var sub = BytesLabels.sub;

var to_string = BytesLabels.to_string;

var of_string = BytesLabels.of_string;

var unsafe_of_string_promise_no_mutation = BytesLabels.unsafe_of_string;

exports.Primitives = Primitives;
exports.max_length = max_length;
exports.blit = blit;
exports.blit_string = blit_string;
exports.compare = compare;
exports.copy = copy;
exports.create = create;
exports.fill = fill;
exports.make = make;
exports.map = map;
exports.mapi = mapi;
exports.sub = sub;
exports.unsafe_blit = unsafe_blit;
exports.to_string = to_string;
exports.of_string = of_string;
exports.unsafe_to_string = unsafe_to_string;
exports.unsafe_of_string_promise_no_mutation = unsafe_of_string_promise_no_mutation;
/* Sys0-Base Not a pure module */
