// Generated by Melange
'use strict';

var Info$negBase = require("./info.bs.js");
var Pretty_printer$negBase = require("./pretty_printer.bs.js");

function raise(t) {
  throw Info$negBase.to_exn(t);
}

function raise_s(sexp) {
  var t = Info$negBase.create_s(sexp);
  throw Info$negBase.to_exn(t);
}

function to_info(t) {
  return t;
}

function of_info(t) {
  return t;
}

var include = Pretty_printer$negBase.Register_pp({
      pp: Info$negBase.pp,
      module_name: "Base.Error"
    });

var compare = Info$negBase.compare;

var equal = Info$negBase.equal;

var hash_fold_t = Info$negBase.hash_fold_t;

var hash = Info$negBase.hash;

var t_of_sexp = Info$negBase.t_of_sexp;

var sexp_of_t = Info$negBase.sexp_of_t;

var t_sexp_grammar = {
  TAG: /* Any */0,
  _0: "Error.t"
};

var invariant = Info$negBase.invariant;

var to_string_hum = Info$negBase.to_string_hum;

var to_string_mach = Info$negBase.to_string_mach;

var to_string_hum_deprecated = Info$negBase.to_string_hum_deprecated;

var of_string = Info$negBase.of_string;

var of_lazy = Info$negBase.of_lazy;

var of_thunk = Info$negBase.of_thunk;

var of_lazy_t = Info$negBase.of_lazy_t;

var create = Info$negBase.create;

var create_s = Info$negBase.create_s;

var createf = Info$negBase.createf;

var tag = Info$negBase.tag;

var tag_s = Info$negBase.tag_s;

var tag_arg = Info$negBase.tag_arg;

var of_list = Info$negBase.of_list;

var of_exn = Info$negBase.of_exn;

var to_exn = Info$negBase.to_exn;

var pp = include.pp;

var Internal_repr = Info$negBase.Internal_repr;

exports.compare = compare;
exports.equal = equal;
exports.hash_fold_t = hash_fold_t;
exports.hash = hash;
exports.t_of_sexp = t_of_sexp;
exports.sexp_of_t = sexp_of_t;
exports.t_sexp_grammar = t_sexp_grammar;
exports.invariant = invariant;
exports.to_string_hum = to_string_hum;
exports.to_string_mach = to_string_mach;
exports.to_string_hum_deprecated = to_string_hum_deprecated;
exports.of_string = of_string;
exports.of_lazy = of_lazy;
exports.of_thunk = of_thunk;
exports.of_lazy_t = of_lazy_t;
exports.create = create;
exports.create_s = create_s;
exports.createf = createf;
exports.tag = tag;
exports.tag_s = tag_s;
exports.tag_arg = tag_arg;
exports.of_list = of_list;
exports.of_exn = of_exn;
exports.to_exn = to_exn;
exports.pp = pp;
exports.Internal_repr = Internal_repr;
exports.raise = raise;
exports.raise_s = raise_s;
exports.to_info = to_info;
exports.of_info = of_info;
/* include Not a pure module */
