// Generated by Melange
'use strict';

var Map_intf$negBase = require("./map_intf.bs.js");

function Check_accessors(T, Tree, Elt, Named, Cmp, Options, M) {
  return {};
}

function Check_accessors0(M) {
  return {};
}

function Check_accessors1(M) {
  return {};
}

function Check_accessors2(M) {
  return {};
}

function Check_accessors2_with_comparator(M) {
  return {};
}

function Check_creators(T, Tree, Elt, Cmp, Options, M) {
  return {};
}

function Check_creators0(M) {
  return {};
}

function Check_creators1(M) {
  return {};
}

function Check_creators2(M) {
  return {};
}

function Check_creators2_with_comparator(M) {
  return {};
}

exports.Check_accessors = Check_accessors;
exports.Check_accessors0 = Check_accessors0;
exports.Check_accessors1 = Check_accessors1;
exports.Check_accessors2 = Check_accessors2;
exports.Check_accessors2_with_comparator = Check_accessors2_with_comparator;
exports.Check_creators = Check_creators;
exports.Check_creators0 = Check_creators0;
exports.Check_creators1 = Check_creators1;
exports.Check_creators2 = Check_creators2;
exports.Check_creators2_with_comparator = Check_creators2_with_comparator;
/* Map_intf-Base Not a pure module */
