// Generated by Melange
'use strict';

var Sys0$negBase = require("./sys0.bs.js");
var Caml_bytes = require("bs-platform/lib/js/caml_bytes.js");
var Import0$negBase = require("./import0.bs.js");
var StringLabels = require("bs-platform/lib/js/stringLabels.js");

var unsafe_blit = Caml_bytes.caml_blit_string;

function concat(sepOpt, l) {
  var sep = sepOpt !== undefined ? sepOpt : "";
  if (l) {
    if (l.tl) {
      return StringLabels.concat(sep, l);
    } else {
      return l.hd;
    }
  } else {
    return "";
  }
}

function iter(t, f) {
  return StringLabels.iter(f, t);
}

var max_length = Sys0$negBase.max_string_length;

var $caret = Import0$negBase.$caret;

var capitalize = StringLabels.capitalize_ascii;

var compare = StringLabels.compare;

var copy = StringLabels.copy;

var escaped = StringLabels.escaped;

var lowercase = StringLabels.lowercase_ascii;

var make = StringLabels.make;

var sub = StringLabels.sub;

var uncapitalize = StringLabels.uncapitalize_ascii;

var uppercase = StringLabels.uppercase_ascii;

exports.max_length = max_length;
exports.$caret = $caret;
exports.capitalize = capitalize;
exports.compare = compare;
exports.copy = copy;
exports.escaped = escaped;
exports.lowercase = lowercase;
exports.make = make;
exports.sub = sub;
exports.uncapitalize = uncapitalize;
exports.unsafe_blit = unsafe_blit;
exports.uppercase = uppercase;
exports.concat = concat;
exports.iter = iter;
/* Sys0-Base Not a pure module */
