// Generated by Melange
'use strict';

var Sys0$negBase = require("./sys0.bs.js");

var get_argv = Sys0$negBase.get_argv;

var argv = Sys0$negBase.argv;

var interactive = Sys0$negBase.interactive;

var os_type = Sys0$negBase.os_type;

var unix = Sys0$negBase.unix;

var win32 = Sys0$negBase.win32;

var cygwin = Sys0$negBase.cygwin;

var backend_type = Sys0$negBase.backend_type;

var word_size_in_bits = Sys0$negBase.word_size_in_bits;

var int_size_in_bits = Sys0$negBase.int_size_in_bits;

var big_endian = Sys0$negBase.big_endian;

var max_string_length = Sys0$negBase.max_string_length;

var max_array_length = Sys0$negBase.max_array_length;

var runtime_variant = Sys0$negBase.runtime_variant;

var runtime_parameters = Sys0$negBase.runtime_parameters;

var ocaml_version = Sys0$negBase.ocaml_version;

var enable_runtime_warnings = Sys0$negBase.enable_runtime_warnings;

var runtime_warnings_enabled = Sys0$negBase.runtime_warnings_enabled;

var getenv = Sys0$negBase.getenv;

var getenv_exn = Sys0$negBase.getenv_exn;

exports.get_argv = get_argv;
exports.argv = argv;
exports.interactive = interactive;
exports.os_type = os_type;
exports.unix = unix;
exports.win32 = win32;
exports.cygwin = cygwin;
exports.backend_type = backend_type;
exports.word_size_in_bits = word_size_in_bits;
exports.int_size_in_bits = int_size_in_bits;
exports.big_endian = big_endian;
exports.max_string_length = max_string_length;
exports.max_array_length = max_array_length;
exports.runtime_variant = runtime_variant;
exports.runtime_parameters = runtime_parameters;
exports.ocaml_version = ocaml_version;
exports.enable_runtime_warnings = enable_runtime_warnings;
exports.runtime_warnings_enabled = runtime_warnings_enabled;
exports.getenv = getenv;
exports.getenv_exn = getenv_exn;
/* Sys0-Base Not a pure module */
